### ISSUE TITLE
Ros/SITL: No heartbeat from FCU with latest master build

### ISSUE THREAD

**Issue by tobiasfriden** [ArduPilot/ardupilot#11933]
### Bug report
I am running ArduCopter/ArduPlane SITL together with ROS in a Docker container.  With the latest build, even though there is an established connection between MavROS and SITL (I can see telemetry data on the ROS topics) there seems to be not heartbeat/capabilities message from the SITL FCU meaning mode cannot be changed etc.

**Version**
Previous build with ArduCopter V3.7.0-dev (062ee711) is working fine,  latest build on commit (be9c98db) is not working.

**Platform**
[  ] All
[  ] AntennaTracker
[x] Copter
[x] Plane
[  ] Rover
[  ] Submarine

**Logs**
When ROS connects with SITL successfully, I can see this log message: 
`[ INFO] [1564658125.687017300]: CON: Got HEARTBEAT, connected. FCU: ArduPilot`
which is missing with the latest build.
Also, `rostopic echo /mavros/state` reports:
```
header: 
  seq: 0
  stamp: 
    secs: 1564658216
    nsecs: 425640000
  frame_id: ''
connected: False
armed: False
guided: False
mode: ''
system_status: 0
```
while on the previous build I can see `connected: True`
